language: node_js
node_js:
  - "7"
  script:
  - npm test

  install:
  - npm install

  services:
  - postgresql

  before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER tznvnvbe WITH PASSWORD 'f9PLh5CImii-y6vaTwevSAKSh50pRi06';" -U postgres

after_success:
- npm run coverage